config/routes.rb
Rails.application.routes.draw do
  resources :air_quality_parameters
  resources :air_quality_parameter_units
  
  resources :data_set_sources
  resources :data_sets
  get '/data_sets/:id/upload_csv', to: 'data_sets#upload_csv'
  post '/data_sets/:id/create_records_from_csv_file', to: 'data_sets#create_records_from_csv_file', as: :create_records_from_csv
	
  get '/air_quality_measurements/search', to: 'air_quality_measurements#search'
  resources :air_quality_measurements
end

app/models/data_set.rb
class DataSet < ApplicationRecord
  belongs_to :data_set_source
  validates_presence_of :name

  def to_s
  	name
  end
end

app/controllers/data_sets_controller.rb
require 'csv'

class DataSetsController < ApplicationController
  before_action :set_data_set, only: [:show, :edit, :update, :destroy, :upload_csv, :select_csv_fields, :create_records_from_csv_file]

  # GET /data_sets
  # GET /data_sets.json
  def index
    @data_sets = DataSet.all
  end

  # GET /data_sets/1
  # GET /data_sets/1.json
  def show
  end

  # GET /data_sets/new
  def new
    @data_set = DataSet.new
  end

  # GET /data_sets/1/edit
  def edit
  end

  # POST /data_sets
  # POST /data_sets.json
  def create
    @data_set = DataSet.new(data_set_params)

    respond_to do |format|
      if @data_set.save
        format.html { redirect_to @data_set, notice: 'Data set was successfully created.' }
        format.json { render :show, status: :created, location: @data_set }
      else
        format.html { render :new }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_sets/1
  # PATCH/PUT /data_sets/1.json
  def update
    respond_to do |format|
      if @data_set.update(data_set_params)
        format.html { redirect_to @data_set, notice: 'Data set was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_set }
      else
        format.html { render :edit }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sets/1
  # DELETE /data_sets/1.json
  def destroy
    @data_set.destroy
    respond_to do |format|
      format.html { redirect_to data_sets_url, notice: 'Data set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_csv
  end

  def create_records_from_csv_file
    #TODO
    # measurements = []
    # CSV.foreach(params[:csv][:file], headers: true) do |row|
    #   byebug
    #   measurements << row.to_h
    # end
    # AirQualityMeasurement.import(items)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_set
      @data_set = DataSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_set_params
      params.require(:data_set).permit(:name, :description, :data_set_source_id, :confidence_level)
    end
end

app/views/data_sets/_form.html.erb
<%= simple_form_for(@data_set) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :data_set_source %>
    <%= f.input :confidence_level %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/data_sets/edit.html.erb
<h1>Editing Data Set</h1>

<%= render 'form', data_set: @data_set %>

<%= link_to 'Show', @data_set %> |
<%= link_to 'Back', data_sets_path %>

app/views/data_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Data set source</th>
      <th>Confidence level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_sets.each do |data_set| %>
      <tr>
        <td><%= data_set.name %></td>
        <td><%= data_set.description %></td>
        <td><%= data_set.data_set_source %></td>
        <td><%= data_set.confidence_level %></td>
        <td><%= link_to 'Show', data_set %></td>
        <td><%= link_to 'Edit', edit_data_set_path(data_set) %></td>
        <td><%= link_to 'Destroy', data_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Set', new_data_set_path %>

app/views/data_sets/new.html.erb
<h1>New Data Set</h1>

<%= render 'form', data_set: @data_set %>

<%= link_to 'Back', data_sets_path %>

app/views/data_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @data_set.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @data_set.description %>
</p>

<p>
  <strong>Data set source:</strong>
  <%= @data_set.data_set_source_id %>
</p>

<p>
  <strong>Confidence level:</strong>
  <%= @data_set.confidence_level %>
</p>

<%= link_to 'Edit', edit_data_set_path(@data_set) %> |
<%= link_to 'Back', data_sets_path %>

app/views/data_sets/upload_csv.html.erb
<%= simple_form_for :csv, method: :post, url: create_records_from_csv_path(@data_set) do |f| %>
  <%= f.file_field :file %>
  <%= f.submit 'Upload' %>
<% end %>