config/routes.rb
Rails.application.routes.draw do
  resources :air_quality_parameters
  resources :air_quality_parameter_units
  
  resources :data_set_sources
  resources :data_sets
  get '/data_sets/:id/upload_csv', to: 'data_sets#upload_csv'
  post '/data_sets/:id/create_records_from_csv_file', to: 'data_sets#create_records_from_csv_file', as: :create_records_from_csv
	
  get '/air_quality_measurements/search', to: 'air_quality_measurements#search'
  resources :air_quality_measurements
end

app/models/air_quality_measurement.rb
class AirQualityMeasurement < ApplicationRecord
  belongs_to :data_set
  belongs_to :air_quality_parameter

  def to_s
  	"#{measurement_datetime} - #{air_quality_parameter} - #{value} #{air_quality_parameter.air_quality_parameter_unit.symbol} [#{data_set}]"
  end
end

app/controllers/air_quality_measurements_controller.rb
class AirQualityMeasurementsController < ApplicationController
  before_action :set_air_quality_measurement, only: [:show, :edit, :update, :destroy]

  # GET /air_quality_measurements
  # GET /air_quality_measurements.json
  def index
    @air_quality_measurements = AirQualityMeasurement.all
  end

  # GET /air_quality_measurements/1
  # GET /air_quality_measurements/1.json
  def show
  end

  # GET /air_quality_measurements/new
  def new
    @air_quality_measurement = AirQualityMeasurement.new
  end

  # GET /air_quality_measurements/1/edit
  def edit
  end

  # POST /air_quality_measurements
  # POST /air_quality_measurements.json
  def create
    @air_quality_measurement = AirQualityMeasurement.new(air_quality_measurement_params)

    respond_to do |format|
      if @air_quality_measurement.save
        format.html { redirect_to @air_quality_measurement, notice: 'Air quality measurement was successfully created.' }
        format.json { render :show, status: :created, location: @air_quality_measurement }
      else
        format.html { render :new }
        format.json { render json: @air_quality_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /air_quality_measurements/1
  # PATCH/PUT /air_quality_measurements/1.json
  def update
    respond_to do |format|
      if @air_quality_measurement.update(air_quality_measurement_params)
        format.html { redirect_to @air_quality_measurement, notice: 'Air quality measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @air_quality_measurement }
      else
        format.html { render :edit }
        format.json { render json: @air_quality_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /air_quality_measurements/1
  # DELETE /air_quality_measurements/1.json
  def destroy
    @air_quality_measurement.destroy
    respond_to do |format|
      format.html { redirect_to air_quality_measurements_url, notice: 'Air quality measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
      @q = AirQualityMeasurement.ransack(params[:q])
      @measurements = @q.result(distinct: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air_quality_measurement
      @air_quality_measurement = AirQualityMeasurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_quality_measurement_params
      params.require(:air_quality_measurement).permit(:data_set_id, :measurement_datetime, :air_quality_parameter_id, :value, :location, :city, :country, :latitude, :longitude, :radius)
    end
end

app/views/air_quality_measurements/_form.html.erb
<%= simple_form_for(@air_quality_measurement) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :data_set %>
    <%= f.input :measurement_datetime %>
    <%= f.association :air_quality_parameter %>
    <%= f.input :value %>
    <%= f.input :location %>
    <%= f.input :city %>
    <%= f.input :country %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :radius %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/air_quality_measurements/edit.html.erb
<h1>Editing Air Quality Measurement</h1>

<%= render 'form', air_quality_measurement: @air_quality_measurement %>

<%= link_to 'Show', @air_quality_measurement %> |
<%= link_to 'Back', air_quality_measurements_path %>

app/views/air_quality_measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Air Quality Measurements</h1>

<table>
  <thead>
    <tr>
      <th>Data set</th>
      <th>Measurement datetime</th>
      <th>Air quality parameter</th>
      <th>Value</th>
      <th>Location</th>
      <th>City</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @air_quality_measurements.each do |air_quality_measurement| %>
      <tr>
        <td><%= truncate air_quality_measurement.data_set.to_s %></td>
        <td><%= l air_quality_measurement.measurement_datetime, format: :short %></td>
        <td><%= air_quality_measurement.air_quality_parameter %></td>
        <td><%= air_quality_measurement.value %></td>
        <td><%= truncate air_quality_measurement.location %></td>
        <td><%= air_quality_measurement.city %></td>
        <td><%= air_quality_measurement.country %></td>
        <td><%= link_to 'Show', air_quality_measurement %></td>
        <td><%= link_to 'Edit', edit_air_quality_measurement_path(air_quality_measurement) %></td>
        <td><%= link_to 'Destroy', air_quality_measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Air Quality Measurement', new_air_quality_measurement_path %>

app/views/air_quality_measurements/new.html.erb
<h1>New Air Quality Measurement</h1>

<%= render 'form', air_quality_measurement: @air_quality_measurement %>

<%= link_to 'Back', air_quality_measurements_path %>

app/views/air_quality_measurements/search.html.erb
<%= search_form_for @q, url: air_quality_measurements_search_path do |f| %>

  <%= f.label :city_cont %>
  <%= f.search_field :city_cont %>

  <%= f.search_field :air_quality_parameter_name_eq %>
  <%= f.submit %>
<% end %>
<br />

<%= @measurements.count %> measurements found for your query.
<br />
Median: <%= @measurements.pluck(:value).median %>
<br />
Mean: <%= @measurements.pluck(:value).mean %>

<br />
<br />

<div id="map" style="height: 400px; width: 600px;"></div>
<br />

<% @measurements.each do |measurement| %>
  <%= measurement %>
  <br />
<% end %>
<script>
  var map, heatmap;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: {lat: <%= @measurements.pluck(:latitude).median %>, lng: <%= @measurements.pluck(:longitude).median %> },
      mapTypeId: 'satellite'
    });

    heatmap = new google.maps.visualization.HeatmapLayer({
      data: getPoints(),
      radius: 4,
      dissipating: false,
      map: map
    });
  }

  // Heatmap data: 500 Points
  function getPoints() {
    return [
    <% @measurements.each do |measurement| %>
      {location: new google.maps.LatLng(<%= measurement.latitude %>, <%= measurement.longitude %>), weight: <%= @measurements.pluck(:value).median %>},
    <% end %>
    ];
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_maps_api_key %>&libraries=visualization&callback=initMap">
</script>

app/views/air_quality_measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data set:</strong>
  <%= @air_quality_measurement.data_set_id %>
</p>

<p>
  <strong>Measurement datetime:</strong>
  <%= @air_quality_measurement.measurement_datetime %>
</p>

<p>
  <strong>Air quality parameter:</strong>
  <%= @air_quality_measurement.air_quality_parameter_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @air_quality_measurement.value %>
</p>

<p>
  <strong>Location:</strong>
  <%= @air_quality_measurement.location %>
</p>

<p>
  <strong>City:</strong>
  <%= @air_quality_measurement.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @air_quality_measurement.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @air_quality_measurement.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @air_quality_measurement.longitude %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @air_quality_measurement.radius %>
</p>

<%= link_to 'Edit', edit_air_quality_measurement_path(@air_quality_measurement) %> |
<%= link_to 'Back', air_quality_measurements_path %>