config/routes.rb
Rails.application.routes.draw do
  resources :air_quality_parameters
  resources :air_quality_parameter_units
  
  resources :data_set_sources
  resources :data_sets
  get '/data_sets/:id/upload_csv', to: 'data_sets#upload_csv'
  post '/data_sets/:id/create_records_from_csv_file', to: 'data_sets#create_records_from_csv_file', as: :create_records_from_csv
	
  get '/air_quality_measurements/search', to: 'air_quality_measurements#search'
  resources :air_quality_measurements
end

app/models/air_quality_parameter_unit.rb
class AirQualityParameterUnit < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :symbol
  validates_uniqueness_of :name
  validates_uniqueness_of :symbol
end

app/controllers/air_quality_parameter_units_controller.rb
class AirQualityParameterUnitsController < ApplicationController
  before_action :set_air_quality_parameter_unit, only: [:show, :edit, :update, :destroy]

  # GET /air_quality_parameter_units
  # GET /air_quality_parameter_units.json
  def index
    @air_quality_parameter_units = AirQualityParameterUnit.all
  end

  # GET /air_quality_parameter_units/1
  # GET /air_quality_parameter_units/1.json
  def show
  end

  # GET /air_quality_parameter_units/new
  def new
    @air_quality_parameter_unit = AirQualityParameterUnit.new
  end

  # GET /air_quality_parameter_units/1/edit
  def edit
  end

  # POST /air_quality_parameter_units
  # POST /air_quality_parameter_units.json
  def create
    @air_quality_parameter_unit = AirQualityParameterUnit.new(air_quality_parameter_unit_params)

    respond_to do |format|
      if @air_quality_parameter_unit.save
        format.html { redirect_to @air_quality_parameter_unit, notice: 'Air quality parameter unit was successfully created.' }
        format.json { render :show, status: :created, location: @air_quality_parameter_unit }
      else
        format.html { render :new }
        format.json { render json: @air_quality_parameter_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /air_quality_parameter_units/1
  # PATCH/PUT /air_quality_parameter_units/1.json
  def update
    respond_to do |format|
      if @air_quality_parameter_unit.update(air_quality_parameter_unit_params)
        format.html { redirect_to @air_quality_parameter_unit, notice: 'Air quality parameter unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @air_quality_parameter_unit }
      else
        format.html { render :edit }
        format.json { render json: @air_quality_parameter_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /air_quality_parameter_units/1
  # DELETE /air_quality_parameter_units/1.json
  def destroy
    @air_quality_parameter_unit.destroy
    respond_to do |format|
      format.html { redirect_to air_quality_parameter_units_url, notice: 'Air quality parameter unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air_quality_parameter_unit
      @air_quality_parameter_unit = AirQualityParameterUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_quality_parameter_unit_params
      params.require(:air_quality_parameter_unit).permit(:name, :symbol)
    end
end

app/views/air_quality_parameter_units/_form.html.erb
<%= simple_form_for(@air_quality_parameter_unit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :symbol %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/air_quality_parameter_units/edit.html.erb
<h1>Editing Air Quality Parameter Unit</h1>

<%= render 'form', air_quality_parameter_unit: @air_quality_parameter_unit %>

<%= link_to 'Show', @air_quality_parameter_unit %> |
<%= link_to 'Back', air_quality_parameter_units_path %>

app/views/air_quality_parameter_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Air Quality Parameter Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @air_quality_parameter_units.each do |air_quality_parameter_unit| %>
      <tr>
        <td><%= air_quality_parameter_unit.name %></td>
        <td><%= air_quality_parameter_unit.symbol %></td>
        <td><%= link_to 'Show', air_quality_parameter_unit %></td>
        <td><%= link_to 'Edit', edit_air_quality_parameter_unit_path(air_quality_parameter_unit) %></td>
        <td><%= link_to 'Destroy', air_quality_parameter_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Air Quality Parameter Unit', new_air_quality_parameter_unit_path %>

app/views/air_quality_parameter_units/new.html.erb
<h1>New Air Quality Parameter Unit</h1>

<%= render 'form', air_quality_parameter_unit: @air_quality_parameter_unit %>

<%= link_to 'Back', air_quality_parameter_units_path %>

app/views/air_quality_parameter_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @air_quality_parameter_unit.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @air_quality_parameter_unit.symbol %>
</p>

<%= link_to 'Edit', edit_air_quality_parameter_unit_path(@air_quality_parameter_unit) %> |
<%= link_to 'Back', air_quality_parameter_units_path %>