config/routes.rb
Rails.application.routes.draw do
  resources :air_quality_parameters
  resources :air_quality_parameter_units
  
  resources :data_set_sources
  resources :data_sets
  get '/data_sets/:id/upload_csv', to: 'data_sets#upload_csv'
  post '/data_sets/:id/create_records_from_csv_file', to: 'data_sets#create_records_from_csv_file', as: :create_records_from_csv
	
  get '/air_quality_measurements/search', to: 'air_quality_measurements#search'
  resources :air_quality_measurements
end

app/models/air_quality_parameter.rb
class AirQualityParameter < ApplicationRecord
  belongs_to :air_quality_parameter_unit
  def to_s
  	name
  end
end

app/controllers/air_quality_parameters_controller.rb
class AirQualityParametersController < ApplicationController
  before_action :set_air_quality_parameter, only: [:show, :edit, :update, :destroy]

  # GET /air_quality_parameters
  # GET /air_quality_parameters.json
  def index
    @air_quality_parameters = AirQualityParameter.all
  end

  # GET /air_quality_parameters/1
  # GET /air_quality_parameters/1.json
  def show
  end

  # GET /air_quality_parameters/new
  def new
    @air_quality_parameter = AirQualityParameter.new
  end

  # GET /air_quality_parameters/1/edit
  def edit
  end

  # POST /air_quality_parameters
  # POST /air_quality_parameters.json
  def create
    @air_quality_parameter = AirQualityParameter.new(air_quality_parameter_params)

    respond_to do |format|
      if @air_quality_parameter.save
        format.html { redirect_to @air_quality_parameter, notice: 'Air quality parameter was successfully created.' }
        format.json { render :show, status: :created, location: @air_quality_parameter }
      else
        format.html { render :new }
        format.json { render json: @air_quality_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /air_quality_parameters/1
  # PATCH/PUT /air_quality_parameters/1.json
  def update
    respond_to do |format|
      if @air_quality_parameter.update(air_quality_parameter_params)
        format.html { redirect_to @air_quality_parameter, notice: 'Air quality parameter was successfully updated.' }
        format.json { render :show, status: :ok, location: @air_quality_parameter }
      else
        format.html { render :edit }
        format.json { render json: @air_quality_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /air_quality_parameters/1
  # DELETE /air_quality_parameters/1.json
  def destroy
    @air_quality_parameter.destroy
    respond_to do |format|
      format.html { redirect_to air_quality_parameters_url, notice: 'Air quality parameter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air_quality_parameter
      @air_quality_parameter = AirQualityParameter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_quality_parameter_params
      params.require(:air_quality_parameter).permit(:name, :description, :air_quality_parameter_unit_id)
    end
end

app/views/air_quality_parameters/_form.html.erb
<%= simple_form_for(@air_quality_parameter) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :air_quality_parameter_unit %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/air_quality_parameters/edit.html.erb
<h1>Editing Air Quality Parameter</h1>

<%= render 'form', air_quality_parameter: @air_quality_parameter %>

<%= link_to 'Show', @air_quality_parameter %> |
<%= link_to 'Back', air_quality_parameters_path %>

app/views/air_quality_parameters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Air Quality Parameters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Air quality parameter unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @air_quality_parameters.each do |air_quality_parameter| %>
      <tr>
        <td><%= air_quality_parameter.name %></td>
        <td><%= air_quality_parameter.description %></td>
        <td><%= air_quality_parameter.air_quality_parameter_unit_id %></td>
        <td><%= link_to 'Show', air_quality_parameter %></td>
        <td><%= link_to 'Edit', edit_air_quality_parameter_path(air_quality_parameter) %></td>
        <td><%= link_to 'Destroy', air_quality_parameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Air Quality Parameter', new_air_quality_parameter_path %>

app/views/air_quality_parameters/new.html.erb
<h1>New Air Quality Parameter</h1>

<%= render 'form', air_quality_parameter: @air_quality_parameter %>

<%= link_to 'Back', air_quality_parameters_path %>

app/views/air_quality_parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @air_quality_parameter.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @air_quality_parameter.description %>
</p>

<p>
  <strong>Air quality parameter unit:</strong>
  <%= @air_quality_parameter.air_quality_parameter_unit_id %>
</p>

<%= link_to 'Edit', edit_air_quality_parameter_path(@air_quality_parameter) %> |
<%= link_to 'Back', air_quality_parameters_path %>